version: '3.2'
services:
  bank-db:
    container_name: ${PROJECT_NAME}-db
    image: mysql:8.0.33
    ports:
      - ${MYSQL_PORT}:${DATABASE_PORT}
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_DATABASE}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - ./mysql-volume:/var/lib/mysql
    networks:
      - bank-network
  bank-backend-dev:
    container_name: ${PROJECT_NAME}-backend-dev
    command: bash -c "rm -rf dist && yarn install && yarn build && yarn run start:dev --debug 0.0.0.0:9228"
    restart: always
    tty: true
    stdin_open: true
    build:
      context: $PWD
      dockerfile: $PWD/docker/App.Dockerfile
      target: development
    volumes:
      - $PWD:/app
    ports:
      - ${PORT}:${PORT}
      - 9228:9228
    networks:
      - bank-network
  bank-redis:
    container_name: '${PROJECT_NAME}-redis'
    restart: on-failure
    image: redis:6.0.8
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - bank-network
networks:
  bank-network:
volumes:
  bank-db:
